### ISSUE TITLE
Analytics

### ISSUE THREAD

**Issue by resynth1943** [damencho/jitsi-desktop-site#1]
Is there a reason why this website uses Google Analytics? Especially since Jitsi is a privacy-focused product, it may be more appropriate to move away from Google Analytics.

**Comment by TheEvilSkeleton** [comment]
I agree with this. Google has been known to be anti-private by collecting a lot of our data and then selling to advertisers without our consent. There are FOSS alternatives to Google Analytics which you can find here: https://developers.reverseeagle.org/replace/google-analytics/

**Comment by Neustradamus** [comment]
@resynth1943: Linked to:
- https://github.com/jitsi/jitsi-desktop-site/issues/2

**Comment by resynth1943** [comment]
@Neustradamus that seems like a duplicate.

I closed this because:

- It's invasive and rude to spam repositories, and for that I'm sorry.
- the person who submitted that issue verbally abused me, and attacked my mental health.

Anyway, good luck in future. Again, sorry for this.
