### ISSUE TITLE
Remove Google Analytics

### ISSUE THREAD

**Issue by TheEvilSkeleton** [damencho/jitsi-desktop-site#2]
Hi!

I'd like to ask if Google Analytics can be removed from the website (maybe Google Fonts as well). Google has been heavily criticized[1][2] for abusing user's data, and there are posts about Google Analytics' problems[3][4]. I would love to see Google Analytics removed from Jitsi's website!

If you still want analytics, then there are FOSS and ethical alternatives listed in this website: https://developers.reverseeagle.org/replace/google-analytics/

[1] https://en.wikipedia.org/wiki/Criticism_of_Google#Privacy
[2] https://en.wikipedia.org/wiki/Privacy_concerns_regarding_Google
[3] https://plausible.io/blog/google-analytics-and-privacy
[4] https://plausible.io/blog/remove-google-analytics

ElementaryOS also has switched to Plausible, and they love it!: https://blog.elementary.io/leaving-google-analytics-is-finally-plausible/

**Comment by damencho** [comment]
I dropped those and just wanted to say that these are not real alternatives to Google Analytics, as they do not offer free service, even for open-source projects.

**Comment by TheEvilSkeleton** [comment]
First off, thank you so much! I really appreciate when developers listen to their users.

But I've noticed that https://jitsi.org uses Google Analytics. It's not really a request, but just wanted to point that out.

![image](https://user-images.githubusercontent.com/50847364/97038207-6dd59d80-1538-11eb-8eea-683fec23ac53.png)

**Comment by Neustradamus** [comment]
Maybe this change will allow a software update...
- https://github.com/jitsi/jitsi

**Comment by TheEvilSkeleton** [comment]
@Neustradamus what so you mean?
