### ISSUE TITLE
FAQ updates: iOS versions exist, also: general FAQ maintenance

### ISSUE THREAD

**Issue by meonkeys** [damencho/jitsi-desktop-site#3]
I'd like to help update https://desktop.jitsi.org/Documentation/FAQ.html#ios since there are now Jitsi iOS mobile apps.

Is desktop.jitsi.org still maintained?

How are edits made to desktop.jitsi.org? I see some mentions of PmWiki but this appears to be a static website (e.g. https://desktop.jitsi.org/Documentation/FAQ?action=edit doesn't support editing ).

**Comment by damencho** [comment]
Jitsi desktop is the legacy desktop client and there are no mobile versions of it. 
It is no longer pmwiki but static files.
